### ISSUE TITLE
[REQ] Add sensory indicators when reaching a threat threshold

### ISSUE THREAD

**Issue by Gogo1951** [dfherr/ThreatClassic2#10]
### What is the feature you would like requested?

As a tank who has to yell at DPS, I would like it if the addon made more alert noises to tell DPS to ease up. More audio cues, more flashing screen cues, basically just spam them with sensory overload until the feign death. (= I'd like those cues to be on by default, but something advanced users could turn off.

**Comment by dfherr** [comment]
This will be implemented soon(TM). There is also already some functionality for this in the addon that needs to be enabled.

**Comment by dfherr** [comment]
will be in the next release.
