### ISSUE TITLE
[BUG] Rogue Combo points

### ISSUE THREAD

**Issue by FedeNoob** [dfherr/ThreatClassic2#104]
### What steps will reproduce the problem?  
1.  Stack combo points on target.
2.  Switch target.
3.  The points from last target will show on the new target.

### What version of ThreatClassic2 are you using? (Stating 'latest' is not useful)
ThreatClassic2-v2.34-bcc

### Do you have an error log of what happened?
No

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

![Combo points](https://user-images.githubusercontent.com/38523397/119409836-34405d00-bce8-11eb-9b8a-1fd8ee43456d.png)

In the pic, i have stacked 2 combo points on the Black Drake, i then switch to the Black Broodling, at it still shows the combo points for the Black Drake. It will reset if i start building on the Broodling.
Its kinda confusing in PVP cuz its fast paced. So sometimes my target dies, and the target i switch to will show points from the old target. So sometimes i think i have stacked points, and i cant stun or whatever :) 
I dont know if i have some weird settings or something, but cant find anything about it.

**Comment by dfherr** [comment]
What makes you think this is related to tc2? I think you want to file a bug with your nameplate addon.

**Comment by FedeNoob** [comment]
Oh fuck, i have clicked the wrong addon, lol Sorry dude.

**Comment by FedeNoob** [comment]
Thought i clicked Threat Plates, TC2 is right under...
