### ISSUE TITLE
[BUG] Config issue

### ISSUE THREAD

**Issue by Zyno** [dfherr/ThreatClassic2#105]
### What steps will reproduce the problem?  
Right click open config.

### What version of ThreatClassic2 are you using? (Stating 'latest' is not useful)
ThreatClassic2-v2.34-bcc

### Do you have an error log of what happened?
Message: ...c2\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:189: attempt to call method 'SetBackdrop' (a nil value)
Time: Wed Jun  2 10:10:09 2021
Count: 3
Stack: ...c2\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:189: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\ThreatClassic2\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua"]:189: in function `?'
[string "@Interface\AddOns\ThreatClassic2\Libs\AceGUI-3.0\AceGUI-3.0.lua"]:108: in function <...AddOns\ThreatClassic2\Libs\AceGUI-3.0\AceGUI-3.0.lua:97>
[string "@Interface\AddOns\ThreatClassic2\Libs\AceGUI-3.0\AceGUI-3.0.lua"]:146: in function `Create'
[string "@Interface\AddOns\ThreatClassic2\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1912: in function `Open'
[string "@Interface\AddOns\ThreatClassic2\core\core.lua"]:950: in function `func'
[string "@Interface\FrameXML\UIDropDownMenu.lua"]:960: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals: frame = <unnamed> {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = <table> {
 bgFile = "Interface\DialogFrame\UI-DialogBox-Background"
 tileSize = 32
 edgeFile = "Interface\DialogFrame\UI-DialogBox-Border"
 tile = true
 edgeSize = 32
 insets = <table> {
 }
}
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
CreateFrame = <function> defined =[C]:-1
UIParent = UIParent {
 0 = <userdata>
 firstTimeLoaded = 1
 variablesLoaded = true
}
FrameBackdrop = <table> {
 bgFile = "Interface\DialogFrame\UI-DialogBox-Background"
 tileSize = 32
 edgeFile = "Interface\DialogFrame\UI-DialogBox-Border"
 tile = true
 edgeSize = 32
 insets = <table> {
 }
}
Frame_OnShow = <function> defined @Interface\AddOns\ThreatClassic2\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:28
Frame_OnClose = <function> defined @Interface\AddOns\ThreatClassic2\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:32
Frame_OnMouseDown = <function> defined @Interface\AddOns\ThreatClassic2\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:36
Button_OnClick = <function> defined @Interface\AddOns\ThreatClassic2\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:23
PaneBackdrop = <table> {
 bgFile = "Interface\ChatFrame\ChatFrameBackground"
 tileSize = 16
 edgeFile = "Interface\Tooltips\UI-Tooltip-Border"
 tile = true
 edgeSize = 16
 insets = <table> {
 }
}
StatusBar_OnEnter = <function> defined @Interface\AddOns\ThreatClassic2\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:71
StatusBar_OnLeave = <function> defined @Interface\AddOns\ThreatClassic2\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:75
Title_OnMouseDown = <function> defined @Interface\AddOns\ThreatClassic2\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:40
MoverSizer_OnMouseUp = <function> defined @Interface\AddOns\ThreatClassic2\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:45
SizerSE_OnMouseDown = <function> defined @Interface\AddOns\ThreatClassic2\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:56
SizerS_OnMouseDown = <function> defined @Interface\AddOns\ThreatClassic2\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:61
SizerE_OnMouseDown = <function> defined @Interface\AddOns\ThreatClassic2\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:66
Type = "Frame"
pairs = <function> defined =[C]:-1
methods = <table> {
 OnHeightSet = <function> defined @Interface\AddOns\ThreatClassic2\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:108
 OnRelease = <function> defined @Interface\AddOns\ThreatClassic2\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:93
 OnWidthSet = <function> defined @Interface\AddOns\ThreatClassic2\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:98
 SetStatusText = <function> defined @Interface\AddOns\ThreatClassic2\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:123
 OnAcquire = <function> defined @Interface\AddOns\ThreatClassic2\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:83
 Show = <function> defi

**Comment by dfherr** [comment]
Thanks for reporting this. it should be fixed in v2.35.

Note that curseforge has a problem with multi client tocs and might not update unless forced.
