### ISSUE TITLE
[REQ] Threat colors on Nameplates

### ISSUE THREAD

**Issue by Mushoz** [dfherr/ThreatClassic2#107]
It would be awesome for Threat colors to be visible on the Stock blizzard nameplates. Would really help when tanking multiple targets for example. Have one HP bar color indicate that I have highest threat, one color that tells me I am still highest threat, but about to be overtaken, and one color for mobs that I am not tanking. Maybe even use gradients instead of 3 set colors. That way it's really easy to see which targets need some attention.

**Comment by dfherr** [comment]
Sorry, but I don't intend to support nameplates in this addon.

There are multiple very well rounded nameplate addons out there that improve your play experience and have this feature built in. Why not give it a try?

Tidyplates even has an optional skin to look like the Blizzard default https://www.curseforge.com/wow/addons/tidy-plates-blizzardplates if you like it that much.
