### ISSUE TITLE
[REQ] Would it be possible to add a filter for the threat window to only show mele dps. 

### ISSUE THREAD

**Issue by TheEye2108** [dfherr/ThreatClassic2#109]
Would it be possible to add a filter for the threat window to only show mele dps. This would help with the gruul fight allot, other filters might be nice also.

**Comment by TheEye2108** [comment]
Just so that this whose already requested. But as a solution for this i would suggest filtering classes and specs, a couple of addons can do it so its possible to get witch class and spec someone has.

**Comment by dfherr** [comment]
yea, i definitely wanna add this and only activatable for specified bosses. will be useful for quite a few.

**Comment by dfherr** [comment]
added in v2.36
