### ISSUE TITLE
[REQ] Inverse Highest/Lowest threat direction in window

### ISSUE THREAD

**Issue by Luc0002** [dfherr/ThreatClassic2#114]
### What is the feature you would like requested?
Very simply, making so an option allows the threat bars to fill from bottom  to top instead of just the default top to bottom within the threat classic window.

**Comment by dfherr** [comment]
i'll see if I can add this with the next update.

**Comment by Luc0002** [comment]
Legend

**Comment by dfherr** [comment]
Sorry didn't have time at all to work on the addon the last months. I found 2 hours tonight and added this. It's released with v2.40.
