### ISSUE TITLE
[REQ] Sound cue's when approaching/overtaking threat leader

### ISSUE THREAD

**Issue by 84h3ufraedmvxc** [dfherr/ThreatClassic2#12]
I remember back in the day Omen used to have configurable sound cue's when your threat was approaching/overtaking the tank. This would be an amazing feature to include.

**Comment by dfherr** [comment]
Hi, this is already on my agenda and a duplicate of https://github.com/dfherr/ThreatClassic2/issues/10

I'll most likely add this in a future version.
