### ISSUE TITLE
[BUG] major lag when resizing the TC2 screen

### ISSUE THREAD

**Issue by Damonenpakt** [dfherr/ThreatClassic2#122]
### What steps will reproduce the problem?  
1.  just try to resize the TC2 screen
2.  
3.  

### What version of ThreatClassic2 are you using? (Stating 'latest' is not useful)
2.5.1

### Do you have an error log of what happened?
no

**Comment by dfherr** [comment]
ah, I fixed that actually but forgot to close the ticket.
