### ISSUE TITLE
[BUG] Issue with Feign Death

### ISSUE THREAD

**Issue by Vendrad** [dfherr/ThreatClassic2#128]
### What steps will reproduce the problem?  
Very hard to reproduce, but something to do with feign > move > server tick. 
Under this condition i believe the server doesn't register the feign but the addon does.

### What version of ThreatClassic2 are you using? (Stating 'latest' is not useful)
2.4.2

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

If you look at the first Gurtogg wipe (fight 70) here, at no point does Tide drop threat due to feign death... https://voomlz.github.io/threat/?id=YTbj9X7dGvnDakwq&fight=cxtRahmV93Pb8YrB;1&enemy=&target=
![image](https://user-images.githubusercontent.com/1723791/156465667-40e39eb5-2ab9-4844-a1de-5f00e758e84e.png)

On stream you can see feign death going off at around 15s in the fight and the addon reporting a drop in threat. I go on to overagro the tank second on threat as the addon reports 10k lower threat than reality... https://www.twitch.tv/videos/1413247977?t=2h20m23s
![image](https://user-images.githubusercontent.com/1723791/156465882-f6c2a942-bce2-4410-9925-fbf5865ab75d.png)

**Comment by dfherr** [comment]
> the server doesn't register the feign but the addon does.

my addon is just displaying the server data since patch 1.13. there is no special feign death handling. what you're seeing in your ingame screenshot is what the Blizzard server believes the threat is.

voomlz.github.io threatcalc on the other hand is doing an estimate based on the log. it tries to be as accurate as possible, but the server is authorative.

**Comment by dfherr** [comment]
Watching your twitch video all looks fine. The palatank gets hit by Bewildering Strike and drops out of threat while disorientied. You are very close to the 2nd tank and probably overshot him for a second between two threat updates exactly when the disorient hit.

**Comment by Vendrad** [comment]
I will admit the post was an effort to understand if there was special handling of feign death, as I remember the change during classic so assumed their wouldn't be.

I suppose the only explanation must be an overagro. Thanks for your input and clarification. 👍
