### ISSUE TITLE
Increase threat update timing[REQ]

### ISSUE THREAD

**Issue by spacct** [dfherr/ThreatClassic2#129]
Is there a way to increase the refresh rate of the addon so that the values? It seems like the refresh rate can be a little slow at pivotal moments when you need to have an updated threat reading.

**Comment by dfherr** [comment]
The addon can only display as recent threat data as the Blizzard API is providing and it trys to update on the `THREAT_LIST_UPDATE` event WoW fires when new threat data is available. There is an update frequency option for healers that get threat via target of target as this event isn't available, but even then it won't display new data until the API provides new data. Reacting to the event is the fastest way to get new threat I am aware of.
