### ISSUE TITLE
[BUG] Alpha color for bar background

### ISSUE THREAD

**Issue by Zhizhica** [dfherr/ThreatClassic2#130]
### What steps will reproduce the problem?  
1.  When Bar Backdrop color alpha value is set to zero, bar backdrop becomes black instead of beeing transparent

### What version of ThreatClassic2 are you using? (Stating 'latest' is not useful)
Version: 2.45 for wrath

### Do you have an error log of what happened?
There is no error log, just incorret behaviour

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)
WoW language: Russian
Screenshot with error.
![image](https://user-images.githubusercontent.com/83887992/191401729-3b81d929-2312-4b02-88c9-23b7953ca9da.png)

I was able to fix this issue by making following changes to [core/core.lua](https://github.com/dfherr/ThreatClassic2/blob/1cb4d862a47b46ba69c67aaf87d990642c8419f6/core/core.lua)
(git diff format)
```diff
@@ -311,7 +311,7 @@ function TC2:UpdateThreatBars()
             bar:SetValue(data.threatPercent)
             local color = GetColor(data.unit, data.isTanking, hasActiveIgnite)
             bar:SetStatusBarColor(unpack(color))
-            bar.bg:SetVertexColor(color[1] * C.bar.colorMod, color[2] * C.bar.colorMod, color[3] * C.bar.colorMod, C.bar.alpha)
+            bar.bg:SetVertexColor(color[1] * C.bar.colorMod, color[2] * C.bar.colorMod, color[3] * C.bar.colorMod, C.backdrop.bgColor[4])

             bar:Show()
         else
@@ -1450,6 +1450,7 @@ TC2.configTable = {
                                 cfg[2] = g
                                 cfg[3] = b
                                 cfg[4] = a
+                                C.backdrop.bgColor = cfg
                                 TC2:UpdateFrame()
                             end,
                         },

```
Screenshot with abovementioned changes:
![image](https://user-images.githubusercontent.com/83887992/191402049-ab57a465-818b-439b-baab-88f0d9e6c21e.png)

Hope it helps!

**Comment by dfherr** [comment]
The issue is that there is an additional background texture fully linked to the bar settings that completely needed to be removed. That makes the backdrop working as expected. I renamed a few settings to apply reasonable defaults for anyone upgrading.

**Comment by dfherr** [comment]
Thanks for reporting btw. Here is how i resolved it:
https://github.com/dfherr/ThreatClassic2/commit/8a38a2b64f85d85ab50275b362d31f5d5c683bbb
