### ISSUE TITLE
WoW Classic Era Update [Version 1.14.4]

### ISSUE THREAD

**Issue by maximus210793** [dfherr/ThreatClassic2#134]
Hi,
first of all, I want to say great adddon!
Could you update it to the latest Classic Era Game Version of 1.14.4?
Would be awesome, thanks a lot in advance!

**Comment by dfherr** [comment]
I already replied to you on curseforge before. Is something not working on classic era? Then it would be really helpful to know what, since I don't play classic era anymore.

If it's just the "outdated" issue, i can fix that easily. But I don't wanna release a broken "up to date" version.

**Comment by maximus210793** [comment]
Just updating the version would be great :)

**Comment by dfherr** [comment]
done.
