### ISSUE TITLE
[BUG] Classic Era Update 1.15.0 (Season of Discovery)

### ISSUE THREAD

**Issue by maximus210793** [dfherr/ThreatClassic2#135]
Hi,
first of all, I want to say great adddon!
Could you update it to the latest Classic Era Game  Version of 1.15.0 (Season of Discovery)?
Would be awesome, thanks a lot in advance!

**Comment by dfherr** [comment]
Any bugs i need to be aware of or is it just a version bump?

**Comment by maximus210793** [comment]
I still getting version 1.14.4 displayed instead of 1.15.0.
Could you please fix this ?
Thank you!

**Comment by dfherr** [comment]
> I still getting version 1.14.4 displayed instead of 1.15.0. Could you please fix this ? Thank you!

i replied to you and asked if there are any bugs except the version bump. That would be immensely helpful in knowing what I need to do.

**Comment by maximus210793** [comment]
No bugs besides the version topic :)
Thanks!
