### ISSUE TITLE
[BUG] Cata core.lua:280 login error

### ISSUE THREAD

**Issue by evilgodly** [dfherr/ThreatClassic2#139]
### What steps will reproduce the problem?  
I get this error right when i login on any of my toons. The addon seems to work with out issue but keep getting this error.   

### What version of ThreatClassic2 are you using? (Stating 'latest' is not useful)
v2.55-cata

### Do you have an error log of what happened?
18x ThreatClassic2/core/core.lua:280: attempt to call field 'GetSpellInfo' (a nil value)
[string "@ThreatClassic2/core/core.lua"]:280: in function `UpdateThreatBars'
[string "@ThreatClassic2/core/core.lua"]:786: in function `UpdateBars'
[string "@ThreatClassic2/core/core.lua"]:686: in function `UpdateFrame'
[string "@ThreatClassic2/core/core.lua"]:995: in function `SetupFrame'
[string "@ThreatClassic2/core/core.lua"]:916: in function `?'
[string "@ThreatClassic2/core/core.lua"]:842: in function <ThreatClassic2/core/core.lua:841>

Locals:
self = <table> {
 colorFallback = <table> {
 }
 FlashScreen = <function> defined @ThreatClassic2/core/core.lua:493
 PLAYER_ENTERING_WORLD = <function> defined @ThreatClassic2/core/core.lua:854
 MenuGenerator = <function> defined @ThreatClassic2/core/core.lua:998
 CheckWarning = <function> defined @ThreatClassic2/core/core.lua:456
 UnregisterComm = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 RefreshProfile = <function> defined @ThreatClassic2/core/core.lua:1038
 partyUnits = <table> {
 }
 UpdateThreatBars = <function> defined @ThreatClassic2/core/core.lua:271
 PLAYER_REGEN_DISABLED = <function> defined @ThreatClassic2/core/core.lua:883
 OnCommReceived = <function> defined @ThreatClassic2/core/core.lua:812
 version = "2.55"
 UpdateBars = <function> defined @ThreatClassic2/core/core.lua:689
 playerClass = ""
 PublishVersion = <function> defined @ThreatClassic2/core/core.lua:829
 SetupConfig = <function> defined @ThreatClassic2/core/core.lua:1025
 partyPetUnits = <table> {
 }
 db = <table> {
 }
 PLAYER_LOGIN = <function> defined @ThreatClassic2/core/core.lua:903
 configTable = <table> {
 }
 raidUnits = <table> {
 }
 SetupFrame = <function> defined @ThreatClassic2/core/core.lua:965
 locale = "enUS"
 UNIT_TARGET = <function> defined @ThreatClassic2/core/core.lua:862
 GROUP_ROSTER_UPDATE = <function> defined @ThreatClassic2/core/core.lua:873
 SendCommMessage = <function> defined @Ace3/AceComm-3.0/AceComm-3.0.lua:83
 defaultConfig = <table> {
 }
 PLAYER_REGEN_ENABLED = <function> defined @ThreatClassic2/core/core.lua:890
 PLAYER_TARGET_CHANGED = <function> defined @ThreatClassic2/core/core.lua:862
 UnregisterAllComm = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 playerTarget = ""
 threatData = <table> {
 }
 UNIT_THREAT_LIST_UPDATE = <function> defined @ThreatClassic2/core/core.lua:896
 ZONE_CHANGED_NEW_AREA = <function> defined @ThreatClassic2/core/core.lua:879
 playerName = ""
 SetupUnits = <function> defined @ThreatClassic2/core/core.lua:950
 RegisterComm = <function> defined @Ace3/AceComm-3.0/AceComm-3.0.lua:56
 TestMode = <function> defined @ThreatClassic2/core/core.lua:792
 frame = ThreatClassic2BarFrame {
 }
 addonName = "ThreatClassic2"
 raidPetUnits = <table> {
 }
 commPrefix = "TC2"
 UpdateFrame = <function> defined @ThreatClassic2/core/core.lua:621
 bars = <table> {
 }
 numGroupMembers = 0
 SetBarCount = <function> defined @ThreatClassic2/core/core.lua:617
}
playerIncluded = false
igniteOwner = nil
hasActiveIgnite = false
(*temporary) = <function> defined =[C]:-1
(*temporary) = 7
(*temporary) = <function> defined @Blizzard_FrameXMLUtil/Classic/AuraUtil.lua:57
(*temporary) = nil
(*temporary) = 12848
(*temporary) = "attempt to call field 'GetSpellInfo' (a nil value)"
sort = <function> defined =[C]:-1
Compare = <function> defined @ThreatClassic2/core/core.lua:177
C = <table> {
 general = <table> {
 }
 backdrop = <table> {
 }
 font = <table> {
 }
 filter = <table> {
 }
 warnings = <table> {
 }
 igniteIndicator = <table> {
 }
 frame = <table> {
 }
 customBarColors = <table> {
 }
 bar = <table> {
 }
}
select = <function> defined =[C]:-1
FindAuraByName = <function> defined @Blizzard_FrameXMLUtil/Classic/AuraUtil.lua:57
TC2 = <table> {
 colorFallback = <table> {
 }
 FlashScreen = <function> defined @ThreatClassic2/core/core.lua:493
 PLAYER_ENTERING_WORLD = <function> defined @ThreatClassic2/core/core.lua:854
 MenuGenerator = <function> defined @ThreatClassic2/core/core.lua:998
 CheckWarning = <function> defined @Inter

**Comment by dfherr** [comment]
this is fixed in 2.55 (cata beta) and now released as full in 2.56
