### ISSUE TITLE
[REQ]Save variables per character rather than per account

### ISSUE THREAD

**Issue by thunk84** [dfherr/ThreatClassic2#14]
### What is the feature you would like requested?
I would like TC2 hidden on my druid, warrior, and paladin when not in a group. I would like it displayed on my warlock and hunter (aka, pet classes) when not in a group. This can be achieved by changing the "SavedVariables" to "SavedVariablesPerCharacter" in the .toc file.

**Comment by dfherr** [comment]
makes sense. will add this in a future release

**Comment by dfherr** [comment]
part of 2.09 and up

**Comment by thunk84** [comment]
I saw the change logs! Thank you!!

___
Tom Basham
