### ISSUE TITLE
[BUG]Got a LUA error at logging in GetSpellName() (a NIL value)

### ISSUE THREAD

**Issue by indrapolak** [dfherr/ThreatClassic2#140]
### What steps will reproduce the problem?  
1.  Logging in WOW
2.  
3.  

### What version of ThreatClassic2 are you using? (Stating 'latest' is not useful)
4.4.1 (Cata Classic)

### Do you have an error log of what happened?
Date: 2024-10-29 22:45:38
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/ThreatClassic2/core/core.lua line 278:
   attempt to call field 'GetSpellName' (a nil value)
Debug:
   [string "=[C]"]: GetSpellName()
   [string "@Interface/AddOns/ThreatClassic2/core/core.lua"]:278: UpdateThreatBars()
   [string "@Interface/AddOns/ThreatClassic2/core/core.lua"]:784: UpdateBars()
   [string "@Interface/AddOns/ThreatClassic2/core/core.lua"]:684: UpdateFrame()
   [string "@Interface/AddOns/ThreatClassic2/core/core.lua"]:993: SetupFrame()
   [string "@Interface/AddOns/ThreatClassic2/core/core.lua"]:914: ?()
   [string "@Interface/AddOns/ThreatClassic2/core/core.lua"]:840:
      Interface/AddOns/ThreatClassic2/core/core.lua:839
Locals:
(*temporary) = <function> defined =[C]:-1

AddOns:
  Swatter, v4.4.7010 (SwimmingSeadragon)
  AtlasLootClassic, vv4.2.0
  AtlasLootClassicData, vv4.2.0
  AtlasLootClassicDungeonsAndRaids, vv4.2.0
  AucAdvanced, v4.4.7010 (SwimmingSeadragon)
  AucFilterBasic, v4.4.7010 (SwimmingSeadragon)
  AucStatHistogram, v4.4.7010 (SwimmingSeadragon)
  AucStatiLevel, v4.4.7010 (SwimmingSeadragon)
  AucStatPurchased, v4.4.7010 (SwimmingSeadragon)
  AucStatSimple, v4.4.7010 (SwimmingSeadragon)
  AucStatStdDev, v4.4.7010 (SwimmingSeadragon)
  AucUtilFixAH, v4.4.7010 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v11.0.21
  Bartender4, v4.15.1
  BeanCounter, v4.4.7010 (SwimmingSeadragon)
  Bistooltip, v8.11
  DBMArnoldEventsPack, v10.1.0
  DBMCore, v11.0.24
  DBMSoundEventsPack, v1.6.37
  DBMSpellTimers, vr158
  DBMStatusBarTimers, v11.0.24
  DBMVPArnoldOriginal, v10.2
  DBMVPVEM, v0481f93
  Decursive, v2.7.23
  Details, v#Details.13132.161
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v4.4.7010 (SwimmingSeadragon)
  EnchantrixBarker, v4.4.7010 (SwimmingSeadragon)
  FloatingCombatTextFix, v2.0.1
  Gargul, v7.6.3
  GatherMate2, v1.47.5-classic
  GuildRosterManager, v1.99154
  HealBot, v4.4.0.43
  HealBotData, v
  HealBotOptions, v
  Informant, v4.4.7010 (SwimmingSeadragon)
  LootReserve, v2024-10-03
  MerfinPlus, v1.43
  NPCTime, v1.0.25
  Pawn, v2.10.3
  Questie, v10.6.4
  SlideBar, v4.4.7010 (SwimmingSeadragon)
  SpellActivationOverlay, v2.3.2
  Stubby, v4.4.7010 (SwimmingSeadragon)
  TacoTip, v0.4.5
  ThreatClassic2, v2.56
  TomTom, vv4.0.3-release
  WeakAuras, v5.17.3
  BlizRuntimeLib v4.4.0.57244(EU) <enUS>
  (ck=68a)

**Comment by dfherr** [comment]
yea i messed up. i released the post patch version one day early. this should fix itself with tomorrows patch
