### ISSUE TITLE
[BUG] Warrior Threat

### ISSUE THREAD

**Issue by rwilliams** [dfherr/ThreatClassic2#15]
### What steps will reproduce the problem?  
1.  Raid or dungeon with a warrior
2.  Watch them be very low on the meter but high on real threat.
3.  See them spike to the top of the list after some delay.

### What version of ThreatClassic2 are you using? (Stating 'latest' is not useful)
2.07 Everyone in raid and in my party had this version too.

### Do you have an error log of what happened?
I was very noticeable in the MC kills.
https://classic.warcraftlogs.com/reports/Lc4AwBvWbQ73DKCk/

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)
Some warriors threat is displayed much lower than it actually its. After some time it will just spike and show the correct value. I believe both warriors were fury/prot hybrid specs. I'll post logs from the raid.

**Comment by dfherr** [comment]
Sounds pretty much like chatthrottle (players are trying to sync too much information across all their addons and are getting throttled).
There is not much I can do about that, but to slow the amount of syncing in general.

However, players can check if they have addons installed using the old `ThreatClassic-1.0`, which provides no value anymore, but contributes to reaching chatthrottle (it sends the same amount of messages as `LibThreatClassic2`). Update these addons (all addons I that I know that used ThreatClassic-1.0 no longer use it, details has it still bundled but doesn't load it, so no problem there).

**Comment by dfherr** [comment]
One more thing: Warriors are currently especially affected, because they sync twice as often as other classes (because the tank is usually a warrior).

In general this is a https://github.com/dfherr/LibThreatClassic2/ problem and not an issue of this addon.

**Comment by dfherr** [comment]
Also duplicate of https://github.com/dfherr/ThreatClassic2/issues/13
