### ISSUE TITLE
[REQ] Support ClassColor colors

### ISSUE THREAD

**Issue by Tanoh** [dfherr/ThreatClassic2#17]
### What is the feature you would like requested?

Support colors set via the ClassColor AddOn, https://www.curseforge.com/wow/addons/classcolors

simple fix:
Change line 39 of core/core.lua to:

    local RAID_CLASS_COLORS = (_G.CUSTOM_CLASS_COLORS or _G.RAID_CLASS_COLORS)

https://github.com/phanx-wow/ClassColors/wiki

**Comment by dfherr** [comment]
part of 2.09 and up
