### ISSUE TITLE
[REQ] Warning Message for Threat Threshold

### ISSUE THREAD

**Issue by gukle** [dfherr/ThreatClassic2#18]
### What is the feature you would like requested?
Can you add a feature that shows a warning when player is above certain threshold?
For example, when bob is above 75% threat, the screen flashes/plays a sound/shows a message until bob drops below 75%? 
Maybe the threshold percentage can be adjusted too.

**Comment by dfherr** [comment]
Duplicate of https://github.com/dfherr/ThreatClassic2/issues/10

yes this is on my todo.
