### ISSUE TITLE
[BUG] Threat is not shown on Vaelastrasz if targetted while friendly

### ISSUE THREAD

**Issue by bjornenalfa** [dfherr/ThreatClassic2#19]
### What steps will reproduce the problem?  
1.  Target Vaelastrasz before fight starts
2.  Fight starts
3.  No threat is shown

### What version of ThreatClassic2 are you using? (Stating 'latest' is not useful)
2.08

### Do you have an error log of what happened?
No

**Comment by dfherr** [comment]
should be fixed in v2.10
