### ISSUE TITLE
Feature request: Show only own Threat %

### ISSUE THREAD

**Issue by heyiamsven** [dfherr/ThreatClassic2#3]
Hello,

I would be pleased if you could implement a option which only show my Threat-Percentage on my screen. 

Example: Similar to this addon for an old game Wildstar: 
https://www.curseforge.com/wildstar/ws-addons/threat/screenshots 

(The last screenshot shows exactly how I expect it to be - Only player threat percentage indicator which can be dragged!)

**Comment by HeavensRejected** [comment]
I second that, given the minimalistic nature of the addon (which I really like) having just a single bar would be fitting in my opinion.
Maybe also add an option to color based on current threat percentage? eg. 0-50 green, 50-70 yellow and 70+ red?
Show tie into my other request coding-wise

**Comment by dfherr** [comment]
You can do that now. The player is always one entry in the addon. Just size the table to 1 and it will only show you and your percentage.
