### ISSUE TITLE
[BUG] Tank has top threat, yet dps/heals has aggro

### ISSUE THREAD

**Issue by lilypure604** [dfherr/ThreatClassic2#31]
### What steps will reproduce the problem?  
1.  Mob drops threat
2.  TC2 isnt reset
3.  Tank still shows top threat, but heals has aggro
~It may not even have to do with the mob dropping threat, but that is an issue, too.
But the main issue is with TC2 showing the tank has top threat and the mob is headed to the healer or dps. I wasn't having this issue with ClassicThreatMeter, but it had its own bugs apparently.

### What version of ThreatClassic2 are you using? (Stating 'latest' is not useful)
v2.11

### Do you have an error log of what happened?
no, video though

**Comment by dfherr** [comment]
Thanks of the report. I'm aware of some issues and try to push out some fixes over the weekend.

> I wasn't having this issue with ClassicThreatMeter

You probably just didn't encounter the same situations. The underlying logic is just an update on classicthreatmeter. From the increasing reports and Blizzards recent activity regard addon syncing it might also be that Blizzard changed something on their side and it impacts tc2...

**Comment by lilypure604** [comment]
Oh yay, fixes! I hope they help a bit :)
Yes you're probably right that I wasn't encountering the same situations,
or maybe the name plate addon I was using with CTM handled it differently
than threat plates handles TC2.
What did they change with addon syncing? If indeed it's because of a
blizzard change, are there alternative ways to make it work as it should?

**Comment by dfherr** [comment]
closing this. probably occured either due to sync problems or missed abilites incorrectly adding bonus threat.
