### ISSUE TITLE
Black Amnesty isn't supported by meter[BUG]

### ISSUE THREAD

**Issue by Puzen** [dfherr/ThreatClassic2#32]
### What steps will reproduce the problem?  
1.  ive simply tried to watch my threat for any drops, should be -540 per proc.
2.  
3.  

### What version of ThreatClassic2 are you using? (Stating 'latest' is not useful)
1.13.3

### Do you have an error log of what happened?
no

**Comment by dfherr** [comment]
Hi I need combat log entries (the ones in `Logs/WoWCombatLog.txt`) showing how the weapon works. Is it a buff, spell cast, debuff or something else?

**Comment by dfherr** [comment]
this will be no longer an issue once the threat api is available in the next patch.
