### ISSUE TITLE
[BUG] Taunt immunity not taken into account

### ISSUE THREAD

**Issue by therealzonder** [dfherr/ThreatClassic2#34]
### What steps will reproduce the problem?  
1.  Have someone use a taunt ability on a taunt-immune mob, their threat will jump up to match MT's 

### What version of ThreatClassic2 are you using? (Stating 'latest' is not useful)
I believe 2.11
We recorded the error Feb 24 and had latest version as of that date

### Do you have an error log of what happened?
No

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

We found this out on Nefarian when a warrior in our group (not MT) reactivity taunted to Nef turning. Nef did not get taunted off (immune), but the warrior's threat jumped from 23K to 70K instantly. We looked back at some of our other fights (ony) and found the same issue.

**Comment by sfpprxy** [comment]
Same issue here.

**Comment by dfherr** [comment]
will be fixed in next version hopefully
