### ISSUE TITLE
[BUG] Lua error

### ISSUE THREAD

**Issue by Altoholic** [dfherr/ThreatClassic2#35]
### What steps will reproduce the problem?  
1.  happened during a resize of the frame (unlock, then move the frame)
actually, it's happening 100% if trying to move the frame while locked.

### What version of ThreatClassic2 are you using? (Stating 'latest' is not useful)
2.11

### Do you have an error log of what happened?
Message: Interface\AddOns\ThreatClassic2\core\core.lua:336: Frame ThreatClassic2BarFrame is not movable
Time: Tue Mar  3 13:02:53 2020
Count: 1
Stack: Interface\AddOns\ThreatClassic2\core\core.lua:336: Frame ThreatClassic2BarFrame is not movable
[C]: in function `StartMoving'
Interface\AddOns\ThreatClassic2\core\core.lua:336: in function <Interface\AddOns\ThreatClassic2\core\core.lua:334>

Locals: (*temporary) = ThreatClassic2BarFrame {
 0 = <userdata>
 resizeTexture = <unnamed> {
 }
 header = <unnamed> {
 }
 resize = ThreatClassic2Resize {
 }
 bg = <unnamed> {
 }
}

**Comment by dfherr** [comment]
thanks for reporting. will be fixed with version 2.13. (forgot this before releasing 2.12)
