### ISSUE TITLE
[REQ] Make bar text info (name, amount, %) optional

### ISSUE THREAD

**Issue by Srljm** [dfherr/ThreatClassic2#36]
### What is the feature you would like requested?

Hello.

I suggest more options for every individual text on the bar.

In particular a checkbox to hide some of these in order to reduce visual clutter.
Dependent on the user settings for bar height and font size it can be difficult to see head to head racing bars for the top spot due to the right side being covered by amount + percentage. I often wish to be able to hide at least the percentage number, because the bar itself is already the indicator for it.

An alternative would be to give font a color transparency setting. This also reduces the contrast from white text to class color which I think makes the bars easier to look at in general. Would be neat to have in any case.

**Comment by karai17** [comment]
Another option would be to have the text not display on the bar, but instead beside the bar.

```
[_Naughtydps____________][109%]
[_Tankoftanks___________][100%]
[_Nicedps________]       [ 73%]
```

**Comment by dfherr** [comment]
Amount and percentage are now optional.
