### ISSUE TITLE
[REQ] Threat coloring for all nameplates and configurable update intervals

### ISSUE THREAD

**Issue by fagitomania** [dfherr/ThreatClassic2#37]
Threat coloring doesnt work. It says "only for blizzards nameplates", but almost everyone uses some nameplate addon. I use neat plates. Can you make it work for all nameplates? Its a very nice addition.

Also allow to set update intervals so we get faster and more responsive threat values

**Comment by dfherr** [comment]
> Threat coloring doesnt work. It says "only for blizzards nameplates", but almost everyone uses some nameplate addon. I use neat plates. Can you make it work for all nameplates? Its a very nice addition.
> 

I can not interact with other nameplate addons. Nameplate addons can use https://github.com/dfherr/LibThreatClassic2 to provide this feature themselves and many do (e.g. threatplates classic or plater, maybe neatplates has it build in.

> Also allow to set update intervals so we get faster and more responsive threat values

The update interval is reasonably set based on the underlying technical details (i.e. threat messages being sent over the network). Any single player is not sending threat updates more often than once every second (all non warriors and tanks are only sending once every 2 seconds), while this addon updates the value once every 0.2 seconds.
