### ISSUE TITLE
[REQ] Threat coloring on the threat meter itself.

### ISSUE THREAD

**Issue by fagitomania** [dfherr/ThreatClassic2#38]
https://github.com/dfherr/ThreatClassic2/issues/37#issuecomment-606258999
You close my previous post very fast and i don't think you understood my request, or i didn't understand your answer.
What i asked was threat coloring on the threat meter itself, not on the nameplates. Like tiny threat from details does it. I want everyone on the threat meter colored according to their threat, not the nameplates. Also an option to disable class colors, have everyone have the same color except my character and the tank. Or i can already do that from the options? I didnt see anything

**Comment by dfherr** [comment]
> What i asked was threat coloring on the threat meter itself, not on the nameplates. Like tiny threat from details does it. I want everyone on the threat meter colored according to their threat, not the nameplates. 

Yes I didn't understand your request. The threat coloring is for blizzard nameplates only.

I do not really intend to replicate all style features of tiny threat. The addon should remain simple.

>Also an option to disable class colors, have everyone have the same color except my character and the tank. Or i can already do that from the options? I didnt see anything

You can't disable class colors currently, but you can select a special color for your character. The option to disable class colors and set everyone else to another color sounds reasonable.

**Comment by fagitomania** [comment]
Well it would be neat, but its ok. Disabling class colors is the feature im most interested about. In the 20 names that appear if i am a mage and theres another 6 mages it can be annoying to search for my name every time.

**Comment by dfherr** [comment]
I suggest just making yourself red for now, so you stick out.

**Comment by fagitomania** [comment]
I prefer your addon, more clear and pleasing on the eye. Tiny threat has some visual issues for me that i really don't like. The making myself red suggestion is actually pretty good. I will do so

**Comment by l-deniau** [comment]
I have modify the code for my guild in order to make the bar coloring more practical (and because our war are reckless...). I put the player on red, tanks assigned on green and the rest on grey. Here an example : 

![image](https://user-images.githubusercontent.com/34558322/80320481-e91ef680-8816-11ea-942f-6685b41a58e8.png)

In order to achieve this, i have modify the file ThreatClsasic2>core>core.lua and replace  the function GetColor(unit) like this :

```lua
local function GetColor(unit)
    if unit then
        local colorUnit = {}

        if C.playerBarCustomColor.enabled and UnitIsUnit(unit, "player") then
            return C.playerBarCustomColor.color
        elseif UnitName(unit)==UnitName("player") then
            colorUnit = {r=183/255, g=28/255, b=28/255} --red
        elseif GetPartyAssignment("MAINTANK", UnitName(unit), True) then
            colorUnit = {r=0/255, g=255/255, b=0/255} --green
        else
            colorUnit = {r=100/255, g=100/255, b=100/255} --grey
        end
        colorUnit = {colorUnit.r, colorUnit.g, colorUnit.b, C.bar.alpha}
        return colorUnit
    else
        return TC2.colorFallback
    end
end
```

Maybe this will help some people :)
