### ISSUE TITLE
[BUG] Frame not shown when entered combat

### ISSUE THREAD

**Issue by wentsa** [dfherr/ThreatClassic2#39]
Frame will not show automatically when entering combat with the option "Hide frame when out of combat" enabled

### What steps will reproduce the problem?  
1.  Set option - "Hide frame when out of combat"
2.  Target any NPC (frame not shown)
3.  Get into combat with that NPC (frame still not shown)
3.  Change target (frame finaly shown)

### What version of ThreatClassic2 are you using?
2.12

**Comment by dfherr** [comment]
will be fixed with next version
