### ISSUE TITLE
Feature request: elvui name plates support

### ISSUE THREAD

**Issue by fletchru** [dfherr/ThreatClassic2#4]
Is it possible to add elvui name plates support same as blizzard's indicators for aggro's color?

**Comment by dfherr** [comment]
I don't really understand the suggestion. Can you clarify?

**Comment by fletchru** [comment]
At present version it is available to turn on "Enable color of threat" (Only for Blizzard's indicators)
Is it possible to add the same threat colors for elvui's indicators ?

**Comment by dfherr** [comment]
No, if this option doesn't work with ElvUi, I don't think it's possible. ElvUI is an addon and if it changes nameplate colors itself there is nothing (reasonable) I can do about it.
