### ISSUE TITLE
[BUG] Cannot find a library instance of "LibThreatClassic2".

### ISSUE THREAD

**Issue by lrxxs** [dfherr/ThreatClassic2#41]
### What steps will reproduce the problem?  
1.When I sign in the game.

### What version of ThreatClassic2 are you using? (Stating 'latest' is not useful)
ThreatClassic2 v2.13

### Do you have an error log of what happened?
AddOns\ThreatClassic2\core\core.lua:85: Cannot find a library instance of "LibThreatClassic2".
Count: 1

Call Stack:
[C]: ?
[C]: in function `error'
AddOns\BigWigs\Libs\LibStub\LibStub.lua:38: in function `GetLibrary'
AddOns\ThreatClassic2\core\core.lua:85: in main chunk

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)
CNwow 1.13.4

**Comment by dfherr** [comment]
Hi, do you get any other errors?

If you go to `World of Warcraft\_classic_\Interface\AddOns\ThreatClassic2\Libs` does it have a `LibThreatClassic2` folder?

How did you install the addon?

**Comment by dfherr** [comment]
I published a new version. However, you might have to edit or reset your settings by deleting your character tc2 settings file found here:

`\World of Warcraft\_classic_\WTF\Account\<your account>\<your server>\<your character>\SavedVariables\ThreatClassic2.lua`

if you don't want to delete it, you can delete the `["name"]` line inside of the `["font"] = {}` settings

**Comment by lrxxs** [comment]
> I published a new version. However, you might have to edit or reset your settings by deleting your character tc2 settings file found here:
> 
> `\World of Warcraft\_classic_\WTF\Account\<your account>\<your server>\<your character>\SavedVariables\ThreatClassic2.lua`
> 
> if you don't want to delete it, you can delete the `["name"]` line inside of the `["font"] = {}` settings

Thank you, I'll try the new version later .
