### ISSUE TITLE
请更新下zhCN文件

### ISSUE THREAD

**Issue by nanjuekaien1** [dfherr/ThreatClassic2#44]
[zhCN.zip](https://github.com/dfherr/ThreatClassic2/files/4585463/zhCN.zip)
@dfherr

**Comment by dfherr** [comment]
thanks, will be released with the next version.

this text is also new in the next version:
L.warnings_minThreatAmount = "Minium threat to display warning."
above a slider to choose an amount between 100 and 20,000 threat before warnings activate.

**Comment by nanjuekaien1** [comment]
@dfherr 
Thank you, I deleted some non-existent files today, and I will send it to you after the next update.

**Comment by nanjuekaien1** [comment]
[zhCN.zip](https://github.com/dfherr/ThreatClassic2/files/4604978/zhCN.zip)
@dfherr

**Comment by dfherr** [comment]
thanks, update will be released with the next version.
