### ISSUE TITLE
Bar Color Issue

### ISSUE THREAD

**Issue by Wowfinal** [dfherr/ThreatClassic2#45]
I am experiencing a bar color issue. Everything within the ThreatClassic2 window appears with a "green tint" and I cannot find the solution. I enabled the original ClassicThreat for comparison on the LEFT, ThreatClassic2 on the Right https://i.imgur.com/pttJ0e5.jpg

**Comment by dfherr** [comment]
did you try changing the texture of the bars? Looks related to the texture. The original texture can be selected as "TC2 Default"

**Comment by dfherr** [comment]
I found a bug that causes this and will release a new version soon.

**Comment by Wowfinal** [comment]
Thank you, looking forward to the update!
