### ISSUE TITLE
Threat percentage doesn't match threat value

### ISSUE THREAD

**Issue by wtfrank** [dfherr/ThreatClassic2#47]
In this image, the tank who has aggro (thern) is listed as 100% threat with 35k. The tank below him (talanken) is listed as 38k threat yet his percentage is shown as 98%.

The percentage threat of talanken should be shown as 38/35 =108% rather than 98%.

![image](https://user-images.githubusercontent.com/1202593/82138590-7acbc380-9819-11ea-9447-c4efe9606d5f.png)

**Comment by dfherr** [comment]
This is absolutely correct. Your 2nd tank is 2% away from pulling aggro. 108/110 = 98. Pulling aggro = 100%. This is the way the Blizzard API works.

If you want raw percentages, there is a config option for that.
