### ISSUE TITLE
[REQ] Custom color for owner of ignite (mages)

### ISSUE THREAD

**Issue by Ayzkronos** [dfherr/ThreatClassic2#48]
I love to use the custom bar colors options. This is what im using at the moment: 
![image](https://user-images.githubusercontent.com/27036775/82791517-328e5000-9e6e-11ea-93ae-56458fe37144.png)

As a mage, i will need to pay attention to whoever is the owner of the Ignite in raids, and be mindful of their threat and how fast it is approaching the tank. In later expansions, each mage had their own ignite debuff on the target, but in vanilla all mages in a raid are contributing to the same ignite stack, and whoever started that ignite (by placing the first out of five stacks) will be creditted all the threat of the ignite.

I would love a feature that allowed me to set a custom color for whichever mage is the owner of the Ignite at any particular time. While i have the ignite, my threat bar turns into the custom color. When the ignite drops off again, my bar returns to my previous setting. Another mage gets the ignite and while he does his bar changes color. That would be incredibly useful. 

Thank you for this addon

**Comment by ShiFangJuMie** [comment]
I have the same idea, but my solution is to read the hate list through WA and sort it

[REQ]How to bridge TC2 and WA? #75

**Comment by dfherr** [comment]
I think that would be a nice feature to have. Or a small ignite icon in front of the player. Have to see if I can realize this. Will become relevant soon.

**Comment by Ayzkronos** [comment]
bump :)

**Comment by dfherr** [comment]
Ignite can now be tracked via custom color and an icon. a bit late, but all the more relevant for naxx I guess :)
