### ISSUE TITLE
Next update plan and time

### ISSUE THREAD

**Issue by nanjuekaien1** [dfherr/ThreatClassic2#49]
@dfherr  The plan and time will be updated next time. Please let me know in advance. I will arrange a good time for localization. Thank you

**Comment by dfherr** [comment]
I just released version 2.20 as preparation for patch 1.13.5. I'll release a new version on the patch day with minimal changes. Would be nice to have translations until then :)

**Comment by nanjuekaien1** [comment]
Start immediately
