### ISSUE TITLE
Change Colour of Threat Bars 

### ISSUE THREAD

**Issue by MishaBurkot** [dfherr/ThreatClassic2#5]
Are you able to make an option to change the colour of the threat bars - instead of just having teal colour?

**Comment by dfherr** [comment]
The bars are colored by the official Blizzard class colors https://wow.gamepedia.com/Class_colors
so I assume you're a mage :)?

I don't intend to add a option to make all bars the same color, why would you want that?

**Comment by HeavensRejected** [comment]
I'd like to have an option to highlight just myself as it can get a bit hard to see yourself when you got 10 warriors in the list.

I haven't really done much addon things in the last 15 years but I "think" the easiest way would be to use GetUnitName ("player") and check the bar for the current player name and change the color then.

**Comment by dfherr** [comment]
> I'd like to have an option to highlight just myself as it can get a bit hard to see yourself when you got 10 warriors in the list.
> 

i'll add an option for this. sounds reasonable.
