### ISSUE TITLE
[REQ] Hide all range option (Ragnaros)

### ISSUE THREAD

**Issue by cdobbyn** [dfherr/ThreatClassic2#50]
### What is the feature you would like requested?
The use case for this is fairly niche, I'm not aware of any other fight where this could be used. 

For Ragnaros, range can go ham without worrying about threat at all. This makes the meters less easy to follow for the melee. It would be helpful to be able to filter out all range on that fight.

Tanks may want to be able to see range threat, to use it for taunting if necessary. So I think this would have to be an option people could turn on and not just a default.

Not sure how feasable something like that would be, but I thought I'd ask.

**Comment by dfherr** [comment]
I see your point. But it's not possible to reliably detect if someone else is in melee range or not (which would be necessary for this feature). You can only detect meele range for yourself (and even that is not entirely reliable).

Also considering Ragnaros resets threat every ~25 secs when he casts his aoe (Wrath of Ragnaros), i'm not sure how useful this feature is to begin with.

However, Omen hhad a feature to disable certain classes, which could be adopted for that.

**Comment by cdobbyn** [comment]
It's for DPS melee (warriors) who will get nuked if the tank can't generate threat fast enough after the Wrath of Ragnaros.

Hiding certain classes would do the job. 

Maybe a "show me and tanks" option, where it literally only shows you and the raid tanks. That could be useful for more than just the Rag fight.

**Comment by ollema** [comment]
this would be super useful for ouro.

as melee, you only really care about other melee when running into melee range after sweep + sand blast.

it gets hard to figure out if the tanks are above you in threat when there is a bunch of mages/warlocks all taking up the top spots in the list

**Comment by dfherr** [comment]
super late, I know, but added in v2.36.

it's configurable for specific targets.
