### ISSUE TITLE
[BUG] Not working

### ISSUE THREAD

**Issue by zb737472783** [dfherr/ThreatClassic2#52]
After updating to v2.20, I found my tc2 doesn't work at all. The threat window only shows myself or 2-3  players at most, and I couldn't open settings by right-click window. I cann't even press "enter" when I type /tc2 in chat window. I tried /rl in game and reinstall but the problem still there.

**Comment by dfherr** [comment]
Please install https://www.curseforge.com/wow/addons/bugsack and https://www.curseforge.com/wow/addons/bug-grabber (you need both. they say retail, but also work for classic!) and post any occuring lua errors.

**Comment by PowershellNinja** [comment]
I do have the same issue (latest version, 2.20), for example only my own threat and that of one other player is displayed although there are others in my party shooting the same enemy and generating threat. I installed both the mentioned addons, but they show no lua errors which is kinda strange as it seems there is something not working property.

**Comment by dfherr** [comment]
@PowershellNinja can you try resizing the addon and enable test mode to see if you see more players? This sounds like your bar number is capped to 2, as you will always see yourself.

**Comment by Beardspec** [comment]
Hello, A few of my guildmates were reporting issues with TC2 last night.  Saying they were showing up as being very high on threat (like 10k+ over the MT), but for me I was not experiencing the same issue.  Specifically on Vael.   Tank was doing 1700-1900 TPS, but rogues thought they were way over the tank and just stopped dps however they were never anywhere close on my meter or the MT meter.

Everyone is updated to the recent version.

**Comment by dfherr** [comment]
@Beardspec sounds unrelated to the issues here and more like a sync issue. Although these are usually only outgoing (i.e. your own meter is different than the ones of everyone else), but not working for some and not working for others like you reported. In any case, this will be fixed once the AQ patch hits live.

**Comment by PowershellNinja** [comment]
@dfherr, I tried to resize and use test mode, that showed easily around 9 threat bars.
Still, yesterday on a Scarlet Monastery run, it continuously ignored the tank and its threat, event after an ui reload:
![ThreatClassic](https://user-images.githubusercontent.com/12686296/86891100-927b4600-c0fe-11ea-98fc-37d6baa94cc1.JPG)

As you can see, Ishiwa is the tank and also has the aggro, still it shows me as having the most threat. Through the whole run, it persistently didn't show the tanks threat, only that of the other 4 players.

**Comment by dfherr** [comment]
closed due to the new threat api.

**Comment by PowershellNinja** [comment]
The new threat api seems to have fixed this, didnt experience it with the newest version :)
