### ISSUE TITLE
[REQ]Interface increment the version number

### ISSUE THREAD

**Issue by nanjuekaien1** [dfherr/ThreatClassic2#54]
### What is the feature you would like requested?
There is a proposal, and DBM can display the version number on the same interface
![版本号](https://user-images.githubusercontent.com/2303601/86012381-79b0c780-ba50-11ea-8973-007760d44295.jpg)

**Comment by dfherr** [comment]
I don't really understand what you want.

Have the interface number in the version number? I see no reason to do that. It's properly document in the toc https://github.com/dfherr/ThreatClassic2/blob/master/ThreatClassic2.toc

**Comment by nanjuekaien1** [comment]
@dfherr  Because after the recent upgrade of version 2.2, some players can’t see the hate list, I can only ask them what version they are. After correcting their opinions based on the version, I found that many people don’t know the version number they installed. Thought, can you show the version number somewhere on the interface.

**Comment by dfherr** [comment]
When you login you get a print out of the current version in chat. I can also add a `/tc2 version command` to print it again.

I had two reports of problems with the threat list, but no one could give me any errors :shrug: so I can't reproduce them

**Comment by nanjuekaien1** [comment]
@dfherr    There are more than two. In CN, I received 4 responses to the problem. If there is no error report, I cannot see the hate list. I told them to use version 2.19.

**Comment by nanjuekaien1** [comment]
@dfherr By the way, DBM removed support for LibThreatClassic2 library files.

**Comment by dfherr** [comment]
> @dfherr There are more than two. In CN, I received 4 responses. If there is no error report, I cannot see the hate list. I told them to use version 2.19.

Version 2.19 will stop working with patch 1.13.5 (coming July 28th in the west). Version 2.20 is prepared for the new patch (it no longer needs LibThreatClassic2) and conditionally loads the threat API if available. Maybe the Chinese WoW client is different and already implements the api, but does not return anything yet? Then this problem might occur.

What does the following command print on a chinese client:

```
/run if _G.UnitThreatSituation ~= nil then print("api available") else print("api not available") end
```

For the EU client it prints `api not available` and everything works as expected.

**Comment by nanjuekaien1** [comment]
@dfherr I also returned   [18:18:26] api not available   。
The problem is, my version 2.2 is fine to see everyone's threat value.

**Comment by nanjuekaien1** [comment]
@dfherr There is another thing I forgot to say， Can restore the function of nameplates.

**Comment by dfherr** [comment]
If they have some other addon installed that sets `UnitThreatSituation` or `UnitDetailedThreatSituation ` globally, then tc2 will stop to work with the changes from version 2.20. However, this would be the fault of the other addon.

**Comment by dfherr** [comment]
> @dfherr There is another thing I forgot to say， Can restore the function of nameplates.

nameplates were no longer working correctly with the new threat api.

there are some good nameplate addons that provide this functionality:

https://www.curseforge.com/wow/addons/plater-nameplates
https://www.curseforge.com/wow/addons/threat-plates-classic

I think tidy plates and neatplates work too:

https://www.curseforge.com/wow/addons/neatplates

neatplates also has a theme to look like default: https://www.curseforge.com/wow/addons/neat-plates-blizzardplates

**Comment by nanjuekaien1** [comment]
@dfherr Okay, back to me, I told them that the plug-in package I integrated with the name board hate function.

**Comment by nanjuekaien1** [comment]
@dfherr Thank you。

**Comment by dfherr** [comment]
> 
> @dfherr Okay, back to me, I told them that the plug-in package I integrated with the name board hate function.

what xD?

**Comment by nanjuekaien1** [comment]
@dfherr Tell them nameplates were no longer working correctly with the new threat api.

**Comment by nanjuekaien1** [comment]
@dfherr I am using  NDuiClassic  
address：https://github.com/siweia/NDuiClassic

**Comment by nanjuekaien1** [comment]
@dfherr You may find that the problem is there, and some people have installed ClassicThreatMeter。

**Comment by nanjuekaien1** [comment]
They have left ClassicThreatMeter in the integrated plug-in. I don’t know if it’s his relationship.

**Comment by dfherr** [comment]
ClassicThreatMeter should be uninstalled under all circumstances. It causes major trouble with addon communication. Blizzard added additional restrictions which makes the issue even worse.

As ThreatClassic2 will use the API from patch 1.13.5 onwards it will no longer be impacted. But keeping ClassicThreatMeter installed still impacts things such as incoming heal display, debuff durations of other players, etc.

**Comment by nanjuekaien1** [comment]
I mean, someone will ask you to say that you can’t see the teammate’s hatred in 2.2, you can ask them to delete their ClassicThreatMeter.
