### ISSUE TITLE
[REQ] Add "reset" option a la KTM

### ISSUE THREAD

**Issue by lvangh** [dfherr/ThreatClassic2#6]
### What is the feature you would like requested?

Add a reset button (for raid leader / assist permissions) that resets the meter to 0 for multi-phase fights like Ony.

**Comment by dfherr** [comment]
I'm not really interested in adding this and rather handle the threat correctly. I.e. this version resets threat on the primary target of the Fireball and also 25% threat reduction on a knockback. This looked pretty accurate on our Onyxia yesterday with about 50% players running the new version.

If threat is handled correctly, there is no need for an incorrect aggro reset. There is no raid-wide aggro reset on Onyxia.

**Comment by dfherr** [comment]
no longer relevant once the threat api hits.
