### ISSUE TITLE
[BUG] Threat no longer displays until player has threat on mob

### ISSUE THREAD

**Issue by karai17** [dfherr/ThreatClassic2#62]
### What steps will reproduce the problem?  
1.  Be in a party with others, or have a pet/minion
2.  Non-player performs actions that apply threat to a mob and also put player into combat

### What version of ThreatClassic2 are you using?
v2.22

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)
Before the Threat API patch, TC2 would display threat on a targetted mob even if the player did not have any threat on that mob. For example, I would watch the threat meter to ensure my pet had enough threat so that when I begin attacking, I won't pull aggro off it.

**Comment by karai17** [comment]
I see you've already addressed this in a closed issue. Cheers~

**Comment by dfherr** [comment]
It's also question number two in the faq :)
