### ISSUE TITLE
[BUG] Bars and % values don't always make sense

### ISSUE THREAD

**Issue by karai17** [dfherr/ThreatClassic2#63]
### What steps will reproduce the problem?  
1.  Do combat things in a party or with a pet/minion

### What version of ThreatClassic2 are you using? (Stating 'latest' is not useful)
v2.22

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

![image](https://user-images.githubusercontent.com/590332/87056644-4dc5dc80-c1dc-11ea-96ed-3b8f8dca503c.png)

![image](https://user-images.githubusercontent.com/590332/87056730-6c2bd800-c1dc-11ea-9d24-0d4055a7a54a.png)

![image](https://user-images.githubusercontent.com/590332/87056753-75b54000-c1dc-11ea-8c3a-da641870b684.png)

![image](https://user-images.githubusercontent.com/590332/87056831-8a91d380-c1dc-11ea-8646-acc7ecc8f0ac.png)

**Comment by dfherr** [comment]
Is this with raw percentages turned on or off?

**Comment by karai17** [comment]
on

**Comment by dfherr** [comment]
The Blizzard API returns wrong values for the raw threat percentage. The addon sorts by the selected threat percentagge so it's a kind of important value. 

I applied a temporary fix that just applies 100% threat percentage for the tank, but will restructure to just calculate this myself.

**Comment by dfherr** [comment]
Thanks for reporting btw. The screenshots were very helpful. Fix is in version 2.23

**Comment by karai17** [comment]
Cheers <3
