### ISSUE TITLE
[BUG] Not showing full right click ->menu options

### ISSUE THREAD

**Issue by cliaz** [dfherr/ThreatClassic2#67]
### What steps will reproduce the problem?  
1.  Right click on TC2 

### What version of ThreatClassic2 are you using? (Stating 'latest' is not useful)
2.23

### Do you have an error log of what happened?
Image 1 below shows what happens when I right click on tc2
Image 2 what I should expect to see, from another in the raid group - https://imgur.com/a/Za6mDfT

We both had Assist rights

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)
![1](https://user-images.githubusercontent.com/3636531/87114319-a2885680-c2b3-11ea-9a75-33763fc8f7c5.png)
![2](https://user-images.githubusercontent.com/3636531/87114323-a4521a00-c2b3-11ea-87d2-3c2ec5e4bad5.png)

**Comment by dfherr** [comment]
Image 1 is what you should see. Image 2 is your slacker raid member who didn't update.

I removed these checks as they were related to the threat library, which was removed due to Blizzard reenabling the threat api.

I added a version announcment if anyone in your guild logs in with a newer version (starting from version 2.21)

**Comment by cliaz** [comment]
Fair enough, thanks for the quick response. 
I relayed this to the raider who sent me the screenshot with the extra options, and he said that he overrides the old with the new by just extracting into the add on folder. Maybe it keeps the old library source files in there where he can check version still.

**Comment by omggga** [comment]
> is not that important anymore

The problem is that now there is no way to check which version the raiders are using - new, old or no tc2 at all.
