### ISSUE TITLE
[BUG] "You are not in a guild." on each login/reload.

### ISSUE THREAD

**Issue by drejjmit** [dfherr/ThreatClassic2#71]
### What steps will reproduce the problem?  
1.  Don't be in a guild. 
2.  Login/reload with ThreatClassic2 activated.
3.  Get message "You are not in a guild."

### What version of ThreatClassic2 are you using? (Stating 'latest' is not useful)
2.23

![image](https://user-images.githubusercontent.com/15526476/87254299-f6489a80-c481-11ea-89c1-c0ffb54cd1c6.png)

**Comment by dfherr** [comment]
Oh yea. I don't check if you're in a guild before doing the version check with the guild. thanks for reporting!

**Comment by dfherr** [comment]
fixed in 2.24. sorry it took so long.
