### ISSUE TITLE
[BUG] Cannot find a library instance of ThreatClassic-1.0

### ISSUE THREAD

**Issue by EGartin** [dfherr/ThreatClassic2#8]
### What steps will reproduce the problem?  
1.  Installed via Twitch App
2.  Enable Addon
3.  Login to game and `/console scriptErrors 1` after being notified of AddOns experiencing a large number of errors and may be slowing down the game.

### What version of ThreatClassic2 are you using? (Stating 'latest' is not useful)
ThreatClassic2-v2.07

### Do you have an error log of what happened?
```
**Message**: [string "--[==[ Error in 'ThreatStatus']==] return ..."]":3: Cannot find a library instance of "ThreatClassic-1.0".
**Time**: Thu Jan 2 15:52:45 2020
**Count**: 3024
**Stack**: [string "--[==[ Error in 'ThreatStatus']==] return ..."]":3: Cannot find a library instance of "ThreatClassic-1.0".
**Locals**: <none>
```
Error happens constantly, several times per second.

**Comment by dfherr** [comment]
Hi @EGartin 

thanks for the reporting this issue.

`ThreatClassic-1.0` is the old library. This addon doesn't use `ThreatClassic-1.0`, so the error can't come  **directly** from this AddOn. However, it could be that some other AddOn expects `ThreatClassic-1.0`. Did you uninstalled something, when you installed `ThreatClassic2`?

Does the error go away, when you disable `ThreatClassic2`?

**Comment by EGartin** [comment]
Hey, sorry about that.  Upon further investigation, looks like it was weak auras I think causing the problem. I had uninstalled the version 1 threat libraries and those other dependencies did not like it.  My cognitive bias just assumed at that point that it was this addon because the only change I had made was remove the old and add the new. 

Thanks for your help! :)
