### ISSUE TITLE
[BUG] core.lua:296: attempt to index local 'bar' (a nil value)

### ISSUE THREAD

**Issue by JackTrapper** [dfherr/ThreatClassic2#83]
### What steps will reproduce the problem?  
1.  
2.  
3.  

### What version of ThreatClassic2 are you using? (Stating 'latest' is not useful)
 - 2.23

### Do you have an error log of what happened?

- **Message**: Interface\AddOns\ThreatClassic2\core\core.lua:296: attempt to index local 'bar' (a nil value)
- **Time**: Sun Aug  2 20:31:46 2020
- **Count**: 2
- **Stack:**
  - Interface\AddOns\ThreatClassic2\core\core.lua:296: attempt to index local 'bar' (a nil value)
  - Interface\AddOns\ThreatClassic2\core\core.lua:296: in function `UpdateThreatBars'
  - Interface\AddOns\ThreatClassic2\core\core.lua:398: in function <Interface\AddOns\ThreatClassic2\core\core.lua:370>
  - Interface\AddOns\ThreatClassic2\core\core.lua:713: in function `?'
  - Interface\AddOns\ThreatClassic2\core\core.lua:687: in function <Interface\AddOns\ThreatClassic2\core\core.lua:686>
- **Locals:** 
   - `self` = &lt;table> {
     - `colorFallback` = &lt;table> { }
     - `partyPetUnits` = &lt;table> { }
     - `partyUnits` = &lt;table> { }
     - `version` = "2.23"
     - `config` = &lt;table> { }
     - `menuTable` = &lt;table> { }
     - `menu` = ThreatClassic2MenuFrame { }
     - `configTable` = &lt;table> { }
     - `db` = &lt;table> { }
     - `raidUnits` = &lt;table> { }
     - `locale` = "enUS"
     - `numGroupMembers` = 0
     - `defaultConfig` = &lt;table> { }
     - `threatData` = &lt;table> { }
     - `playerName` = "Redacted"
     - `playerTarget` = "target"
     - `raidPetUnits` = &lt;table> {  }
     - `commPrefix` = "TC2"
     - `frame` = ThreatClassic2BarFrame {  }
     - `bars` = &lt;table> {  }
     - `addonName` = "ThreatClassic2"
 - `playerIncluded` = false
 - `data` = &lt;table> {
   - `isTanking` = true
   - `threatValue` = 3918
   - `threatPercent` = 100
   - `unit` = "player"
 - `bar` = nil

### Any additional information? (example: WoW language if not English) (Attach screenshots here if available, do not link externally)

I configured the bar width, height, and font, to be smaller. I probably slid the sliders to their minimum value by mistake; that's when the error started - even after sliding the sliders back up again the errors continued. The only way to resolve it was to **Reset** the profile

**Comment by nanjuekaien1** [comment]
@JackTrapper  All other plug-ins are disabled and tc2 is turned on separately. Does it still report an error?

**Comment by dfherr** [comment]
Thanks for the report. Have to check it out. Looks like a missing safe-guard for an unsupported value. Glad resetting solved the error though.

**Comment by JackTrapper** [comment]
>  Have to check it out. 

I can reproduce it if i drag **Height** taller (**Position** -> **Height**):

![image](https://user-images.githubusercontent.com/4681474/89185524-5e157100-d568-11ea-80c1-133730487f22.png)

**Comment by dfherr** [comment]
fixed. thanks again for reporting. the issue was that the bar logic is limited to 40 players, but bar count calculation was based on height. if your height supported more than 40 players, it freaked out :)
