### ISSUE TITLE
Update aggro one pet attack

### ISSUE THREAD

**Issue by andreasOB** [dfherr/ThreatClassic2#86]
Hi. Is it possible to get the threat to start working once a hunters pet attack an enemy?
That would have helped to know when to start attacking while levling pets and such.

**Comment by dfherr** [comment]
No. It's not possible. See https://github.com/dfherr/ThreatClassic2/issues/56

**Comment by andreasOB** [comment]
Thanks for the reply. And also thanks for making this addon so great :)
